<a href="https://colab.research.google.com/github/arikrishnan123/Data-Science/blob/main/practical%20program.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
import numpy as np
a=np.array([(1,2,3), (4, 5, 6)])
print(a)

[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np
np.random.seed(0) # seed for reproducibility
x1 = np.random.randint(10, size=6) # One-dimensional array
x2 = np.random.randint(10, size=(2, 4)) # Two-dimensional array
print (x1)
print(x2)

[5 0 3 3 7 9]
[[3 5 2 4]
 [7 6 8 8]]


In [9]:
import numpy as np
a=np.array([(1,2,3), (4, 5, 6)])
print(a.ndim)

2


In [8]:
import numpy as np
a=np.array([(1,2,3)])
print(a.itemsize)

8


In [11]:
import numpy as np
a=np.array([(1,2,3)])
print(a.dtype)

int64


In [13]:
import numpy as np
a = np.array([(1,2,3,4,5,6)])
print(a.size)
print(a.shape)

6
(1, 6)


In [14]:
import numpy as np
a = np.array([(8,9,10),(11,12,13)])
print(a)
a=a.reshape(3,2)
print(a)

[[ 8  9 10]
 [11 12 13]]
[[ 8  9]
 [10 11]
 [12 13]]


In [20]:
import numpy as np
a=np.array([1,2,3])
print(a.min())
print(a.max())

1
3


In [21]:
import numpy as np
a= np.array([(1,2,3,4),(3,4,5,6)])
print(a[0,2])

3


In [22]:
x=np.array([(1,2,3),(3,4,5)])
y=np.array([(1,2,3),(3,4,5)])
print(x+y)
print(x-y)
print(x*y)
print(x/y)

[[ 2  4  6]
 [ 6  8 10]]
[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [ 9 16 25]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [23]:
import numpy as np
a=np.array([(1,2,3),(3,4,5)])
print(np.sqrt(a))

[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]


In [24]:
x = [1, 2, 4, 10]
print("x =", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

x = [1, 2, 4, 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [26]:
import pandas as pd
import numpy as np
import statistics as st
# Load the data
from google.colab import files
uploaded = files.upload()
df = pd.read_csv("diabetes.csv")
print(df.shape)
print(df.info())

Saving diabetes.csv to diabetes.csv
(10, 9)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               10 non-null     int64  
 1   Glucose                   10 non-null     int64  
 2   BloodPressure             10 non-null     int64  
 3   SkinThickness             10 non-null     int64  
 4   Insulin                   10 non-null     int64  
 5   BMI                       10 non-null     float64
 6   DiabetesPedigreeFunction  10 non-null     float64
 7   Age                       10 non-null     int64  
 8   Outcome                   10 non-null     int64  
dtypes: float64(2), int64(7)
memory usage: 852.0 bytes
None


In [30]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   
5            5      116             74              0        0  25.6   
6            3       78             50             32       88  31.0   
7           10      115              0              0        0  35.3   
8            2      197             70             45      543  30.5   
9            8      125             96              0        0   0.0   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1  
5                     0.201   30        0  
6                     0.248   26        1  
7                     0.134   29        0  
8                     0.158   53        1  
9                     0.232   54        1

In [27]:
df['BMI'].value_counts()

BMI
33.6    1
26.6    1
23.3    1
28.1    1
43.1    1
25.6    1
31.0    1
35.3    1
30.5    1
0.0     1
Name: count, dtype: int64

In [28]:
df.mean()

Pregnancies                   4.4000
Glucose                     127.3000
BloodPressure                59.8000
SkinThickness                19.9000
Insulin                      89.3000
BMI                          27.7100
DiabetesPedigreeFunction      0.5078
Age                          35.9000
Outcome                       0.6000
dtype: float64

In [29]:
df.mean(axis = 1)[0:5]

0    38.469667
1    26.550111
2    34.663556
3    35.807444
4    51.043111
dtype: float64

In [31]:
df.mode()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0          1.0       78           66.0            0.0      0.0   0.0   
1          8.0       85            NaN            NaN      NaN  23.3   
2          NaN       89            NaN            NaN      NaN  25.6   
3          NaN      115            NaN            NaN      NaN  26.6   
4          NaN      116            NaN            NaN      NaN  28.1   
5          NaN      125            NaN            NaN      NaN  30.5   
6          NaN      137            NaN            NaN      NaN  31.0   
7          NaN      148            NaN            NaN      NaN  33.6   
8          NaN      183            NaN            NaN      NaN  35.3   
9          NaN      197            NaN            NaN      NaN  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.134   21      1.0  
1                     0.158   26      NaN  
2                     0.167   29      NaN  
3                     0.201   30      NaN  
4                     0.232   31      NaN  
5                     0.248   32      NaN  
6                     0.351   33      NaN  
7                     0.627   50      NaN  
8                     0.672   53      NaN  
9                     2.288   54      NaN

In [32]:
df.std()

Pregnancies                   3.502380
Glucose                      40.075068
BloodPressure                25.654976
SkinThickness                17.978073
Insulin                     169.937276
BMI                          11.259016
DiabetesPedigreeFunction      0.654114
Age                          11.873874
Outcome                       0.516398
dtype: float64